version: '3.8'

services:
  web:
    build: .
    command: gunicorn practice.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - pgdb
      
  pgdb:
    image: postgres:13.0-alpine
    env_file:
      - ./.env.dev.db
    container_name: pgdb
    # expose:
    #   - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: