# Generated by Django 4.2.3 on 2023-08-05 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%ContactID'),
        ),
        migrations.AddField(
            model_name='contact',
            name='timeCreate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 5, 19, 10, 26, 352637, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='timeUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
