# Generated by Django 4.2.3 on 2023-08-14 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactManager', '0003_alter_contact_birthday_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+[1-9]\\d{1,16}$')]),
        ),
    ]
