# Generated by Django 4.2.4 on 2023-08-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactManager', '0005_group_contact_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='group_id',
            new_name='group',
        ),
    ]
