# Generated by Django 4.2.4 on 2023-08-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactManager', '0006_rename_group_id_contact_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
