# Generated by Django 4.2.3 on 2023-08-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameLocal', models.CharField(max_length=255)),
                ('favorite', models.BooleanField()),
            ],
        ),
    ]
